
package es.unican.ss.volumenArea;

import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "SOAPPort", serviceName = "VolumenArea", targetNamespace = "http://www.unican.es/ss/VolumenArea/", wsdlLocation = "file:/c:/SS_Practicas/Practica2/src/main/resources/VolumenArea.wsdl", endpointInterface = "es.unican.ss.volumenArea.VolumenAreaInterface")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class VolumenArea_SOAPPortImpl
    implements VolumenAreaInterface
{


    public VolumenArea_SOAPPortImpl() {
    }

    /**
     * Retorna el area del objeto dado
     * 
     * @param params
     * @return
     *     returns double
     * @throws DatosNoValidosException
     */
    public double area(Dimensiones params)
        throws DatosNoValidosException
    {
        return params.ancho * params.largo;
    }

    /**
     * Retorna el volumen del objeto dado
     * 			
     * 
     * @param params
     * @return
     *     returns double
     * @throws DatosNoValidosException
     */
    public double volumen(Dimensiones params)
        throws DatosNoValidosException
    {
        return params.alto * params.largo * params.ancho;
    }

}
