
package es.unican.ss.EstimacionesTUSClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "EstimacionesTUSService", targetNamespace = "http://www.unican.es/ss/SSEstimacionesTUS", wsdlLocation = "http://localhost:8080/SSEstimacionesTUS?wsdl")
public class EstimacionesTUSService
    extends Service
{

    private final static URL ESTIMACIONESTUSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ESTIMACIONESTUSSERVICE_EXCEPTION;
    private final static QName ESTIMACIONESTUSSERVICE_QNAME = new QName("http://www.unican.es/ss/SSEstimacionesTUS", "EstimacionesTUSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SSEstimacionesTUS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTIMACIONESTUSSERVICE_WSDL_LOCATION = url;
        ESTIMACIONESTUSSERVICE_EXCEPTION = e;
    }

    public EstimacionesTUSService() {
        super(__getWsdlLocation(), ESTIMACIONESTUSSERVICE_QNAME);
    }

    public EstimacionesTUSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTIMACIONESTUSSERVICE_QNAME, features);
    }

    public EstimacionesTUSService(URL wsdlLocation) {
        super(wsdlLocation, ESTIMACIONESTUSSERVICE_QNAME);
    }

    public EstimacionesTUSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTIMACIONESTUSSERVICE_QNAME, features);
    }

    public EstimacionesTUSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstimacionesTUSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEstimacionesTUS
     */
    @WebEndpoint(name = "EstimacionesTUSPort")
    public IEstimacionesTUS getEstimacionesTUSPort() {
        return super.getPort(new QName("http://www.unican.es/ss/SSEstimacionesTUS", "EstimacionesTUSPort"), IEstimacionesTUS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEstimacionesTUS
     */
    @WebEndpoint(name = "EstimacionesTUSPort")
    public IEstimacionesTUS getEstimacionesTUSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.unican.es/ss/SSEstimacionesTUS", "EstimacionesTUSPort"), IEstimacionesTUS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTIMACIONESTUSSERVICE_EXCEPTION!= null) {
            throw ESTIMACIONESTUSSERVICE_EXCEPTION;
        }
        return ESTIMACIONESTUSSERVICE_WSDL_LOCATION;
    }

}
