
package es.unican.ss.EstimacionesTUSClient;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IEstimacionesTUS", targetNamespace = "http://www.unican.es/ss/SSEstimacionesTUS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEstimacionesTUS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "proximosAutobuses", targetNamespace = "http://www.unican.es/ss/SSEstimacionesTUS", className = "es.unican.ss.EstimacionesTUSClient.ProximosAutobuses")
    @ResponseWrapper(localName = "proximosAutobusesResponse", targetNamespace = "http://www.unican.es/ss/SSEstimacionesTUS", className = "es.unican.ss.EstimacionesTUSClient.ProximosAutobusesResponse")
    @Action(input = "http://www.unican.es/ss/SSEstimacionesTUS/IEstimacionesTUS/proximosAutobusesRequest", output = "http://www.unican.es/ss/SSEstimacionesTUS/IEstimacionesTUS/proximosAutobusesResponse")
    public String proximosAutobuses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
